sudo: enabled
dist: trusty

language: node_js

node_js:
  - "stable"

# script:
#   - mkdir /tmp/pip_build_root

cache:
  yarn: true
  pip3: true
  custom_install: true
  directories:
    - node_modules
    # - /usr/lib/python3/dist-packages
    # - /usr/local/lib/python3.4/dist-packages
    - $HOME/.cache/pip3

notifications:
  email:
    recipients:
      # - xamgore+travis@ya.ru
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"

addons:
  apt:
    packages:
      - "sshpass"
      - "python3"
      - "python3-pip"

before_install:
  - sudo add-apt-repository ppa:bauruine/sshpass -y
  - sudo apt-get update -q

install:
  - sudo pip3 install regex lxml requests textile cssselect jinja2

before_script:
  - (cd ast && yarn)
  # - (cd telegram && yarn)
  - sudo chmod +x ./script/build.sh

script: ./script/build.sh

# after_success:
#   - Rscript -e 'library(covr); codecov(token = "[key-here]")'
