sudo: enabled
dist: trusty

language: node_js

node_js:
  - "stable"

python:
  - "3.6"

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email:
    recipients:
      # - xamgore+travis@ya.ru
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

install:
  - sudo pip3 install regex lxml requests textile cssselect

before_script:
  - (cd ast && yarn)
  - sudo chmod +x ./script/build.sh

script: ./script/build.sh

# matrix:
#   include:
#     - language: node_js
#       script: cd ast && yarn
#       cache: yarn
#     - script: chmod +x ./script/build.sh
#       # script: ./script/cibuild

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.


# TODO: include js, run html-proofer
# https://jekyllrb.com/docs/continuous-integration/travis-ci/
# https://ayastreb.me/deploy-jekyll-to-github-pages-with-travis-ci/
