sudo: enabled
dist: trusty

language: node_js

node_js:
  - "stable"

python:
  - "3.6"

cache:
  yarn: true
  directories:
    - node_modules
    - /usr/lib/python3/dist-packages

notifications:
  email:
    recipients:
      # - xamgore+travis@ya.ru
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"

addons:
  apt:
    packages:
      - "python3"
      - "python3-pip"

install:
  - sudo pip3 install regex lxml requests textile cssselect

before_script:
  - (cd ast && yarn)
  - sudo chmod +x ./script/build.sh

script: ./script/build.sh
